### ISSUE TITLE
Trigger script on location change

### ISSUE THREAD

**Issue by beltranrengifo** [eprev/locationchanger#16]
Hello! 

The location switching is working fine and the tail shows normal activity.
But, I want to trigger a small script to install some proxy config for npm and git. For example, when I switch to "work" wifi network, I want to run `npm config set proxy http://myproxy.com:8080 && npm config set https-proxy http://myproxy.com:8080`.

Now, inside `./locations` i have a file named the same as the wifi network with this script:

```
#!/usr/bin/env bash
exec 2>&1
npm config set proxy http://myproxy.com:8080 && npm config set https-proxy http://myproxy.com:8080 && git config --global http.proxy http://myproxy.com:8080
```

And the same in another file called `Automatic` but in reverse, to remove the proxy when not at work.

The tail does not show anything related to the scripts... What am I missing?
Thank you!!

**Comment by kyletmiller** [comment]
A couple questions, if I may:

1) does your locationchanger log ($HOME/Library/Logs/LocationChanger.log by default) show a message similar to: "Running '$SCRIPT'" (where's $SCRIPT is your location/script name)?

2) Can you confirm the scripts are executable (to make them executable, run: `chmod +x $HOME/.locations/$SCRIPT`)?

3) Depending on the location of your npm & git executables, they may or may not be in your script's PATH. Consider using the full paths to npm & git if it's not in a standard location or verifiably in your script's PATH.

If you're able to attach your log file, that may aid in troubleshooting as well.

**Comment by beltranrengifo** [comment]
Hi!
Thanks for your help.

1. After making executable the scrips, as you describe in point 2, I see in the log the message, but not before. Now I see this when I change the location:

```
[2019-04-26 20:39:50] Connected to 'MOVISTAR_81A6'
[2019-04-26 20:39:50] Location 'MOVISTAR_81A6' was not found. Will default to 'Automatic'
[2019-04-26 20:39:50] Changing the Location to 'Automatic'
CurrentSet updated to AB296F68-2008-4C1E-9F4C-55B901D8510F (Automatic)
[2019-04-26 20:39:50] Running script: '/Users/belt/.locations/Automatic'
[2019-04-26 20:40:17] Connected to 'Jajaja'
[2019-04-26 20:40:17] Location 'Jajaja' was found and matches the SSID. Will switch the Location to 'Jajaja'
[2019-04-26 20:40:17] Changing the Location to 'Jajaja'
CurrentSet updated to 79D35D1E-E62E-4D7F-BCB3-1A6D4DF8BECD (Jajaja)
[2019-04-26 20:40:17] Running script: '/Users/belt/.locations/Jajaja'
```

2. I made it just now, as I said, after your message.

3. Npm config shows this:

`npm config get`
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.15.0 darwin x64"

; node bin location = /Users/belt/.nvm/versions/node/v10.15.0/bin/node
; cwd = /Users/belt
; HOME = /Users/belt
; "npm config ls -l" to show all defaults. 
```

It should be some proxy settings in there... The `Jajaja` script contains this:

```
#!/usr/bin/env bash
exec 2>&1
npm config set proxy http://myproxy.com:8080 && npm config set https-proxy http://myproxy.com:8080 && git config --global http.proxy http://myproxy.com:8080
```

Thank you!

**Comment by kyletmiller** [comment]
Good progress!

It appears that locationchanger is properly running the script now. A few more things to check:

1) does the script work as expected when executed directly?

2) since locationchanger spawns a subshell with the script, your full bash environment may not be available to it. Common problems here include things like the $PATH variable not being set correctly for the script(s) to run in a subshell. I'm not much of an npm user so can't speak to it directly, but I was able to execute `npm config` commands from a script spawned by locationchanger once I tidied up its environment (specifically the $PATH variable). I personally set up my $PATH variable in ~/.bash_profile.

If you do something similar, simply adding "source ${HOME}/.bash_profile" underneath your shebang might very well be sufficient.

You can also set the environment variables directly from your new script. For this method, I might suggest replicating your interactive bash environment to get started. Type "echo $PATH" at the command line to see your current path (a colon-delimited list of directories), then copy the text and insert it accordingly, under the shebang in your script:

export PATH=<paste your copied list here>:$PATH

**Comment by beltranrengifo** [comment]
Hi!

1. Yes, the scripts work fine if I execute them:
`sh ./Jajaja`

```
npm config get
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.15.0 darwin x64"

; userconfig /Users/belt/.npmrc
https-proxy = "http://proxy.indra.es:8080/"
proxy = "http://proxy.indra.es:8080/"

; node bin location = /Users/belt/.nvm/versions/node/v10.15.0/bin/node
; cwd = /Users/belt
; HOME = /Users/belt
; "npm config ls -l" to show all defaults.

```

You can see the proxy settings there. Same for `Automatic`script.

2. I do not deeply understand this point. I tried with no luck using `source` command. I hve to check and try to understand the $PATH variable...

The last method, setting the env vars in the script, worked!:

```
#!/usr/bin/env bash
exec 2>&1
export PATH=:/Users/belt/.nvm/versions/node/v10.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm config set proxy http://myproxy.com:8080 && npm config set https-proxy http://myproxy.com:8080 && git config --global http.proxy http://myproxy.com:8080
```

May I ask you if you can clarify me a little bit more what is going on with the subshell and the path var?

Thank you!

**Comment by eprev** [comment]
Thank you @kyletmiller for the help!

> May I ask you if you can clarify me a little bit more what is going on with the subshell and the path var?

As I can see, you use NVM, and for some reason, the path to the current node version (`/Users/belt/.nvm/versions/node/v10.15.0/bin`) is not set in subshell. For the record, subshell doesn't read `.bash_profile` file, but `.bashrc`. Could you check if NVM was setup in `.bashrc`?

**Comment by beltranrengifo** [comment]
Hi!

I can't find any .bashrc file in my user directory...

**Comment by eprev** [comment]
@beltranrengifo that may explain why the `$PATH` variable is not complete. Sourcing `.bash_profile`(i.e.`source ~/.bash_profile`) in `.bashrc` should solve it.
