### ISSUE TITLE
Does Location not associate a specific SSID?

### ISSUE THREAD

**Issue by NoSloppy** [eprev/locationchanger#18]
Hi! I saw locationchanger as a background shortcut that I could implement by changing the WiFi I am connected to. Trying to have Location change when I select a different WiFi network, because I need DHCP for one and manually set static for the other. However, it seems manually switching locations, I don't get chosen SSID saved with the location when hitting Apply. If it's not associated with the location, then location changer wouldn't help.
Also, I don't see location changer doing anything when manually changing WiFi networks from the menu bar icon. Is it meant to only work when airport discovers SSID and/or loses one due to proximity? Does MacOS' Location not include storing the SSID with the Location? Sorry if that's not clear.
Thanks.

**Comment by eprev** [comment]
Hi! I think you got it wrong, locationchanger doesn’t connect you to a certain Wi-Fi network, it does the opposite – when you connect to a certain Wi-Fi network it changes the network location accordingly. So, it won’t help in your case. And I don’t think the network location keeps the name of the wi-fi network you are connected to (it’s a bummer).

**Comment by NoSloppy** [comment]
Hey thanks for the reply. I understand what it's supposed to do so it can
work for me. I'm going to manually choose the Wi-Fi SSID from the menu bar
icon. That should change my location to one that is set for TCP/IP manual
static IP address. The problem is, nothing is triggering when I change
Wi-Fi. Is the service permission restricted possibly? I've rebooted to no
avail.

**Comment by NoSloppy** [comment]
Hey never mind I found the problem. You forgot locationchanger on the end
of the destination path in the install script, so it copied the
locationchanger executable to /usr/local/bin, making bin the executable,
not a directory containing an executable named locationchanger.

**Comment by NoSloppy** [comment]
Although, that really shouldn't your problem because cp should have put it
in bin, not replace it. so forgetting all that, now I have it triggering,
but it always says automatic

**Comment by eprev** [comment]
Could you paste the logs here `tail -f ~/Library/Logs/LocationChanger.log`?

**Comment by NoSloppy** [comment]
I got it working, thanks for everything.
