### ISSUE TITLE
Does not finish installation [help wanted] [bug]

### ISSUE THREAD

**Issue by NathanBlais** [eprev/locationchanger#19]
I have tried to install it multiple times, but it keeps getting held up by something. It never gets to making the .locations folder so something is not working for me.

This is what I get when I run the code with some extra output. Otherwise it thinks that is is fully installed even though it is not running most of the script. 

```
xxx$ bash -x locationchanger.sh
+ INSTALL_DIR=/usr/local/bin
+ SCRIPT_NAME=/usr/local/bin/locationchanger
+ LAUNCH_AGENTS_DIR=/Users/nathanblais/Library/LaunchAgents
+ PLIST_NAME=/Users/nathanblais/Library/LaunchAgents/LocationChanger.plist
+ sudo -v
+ sudo mkdir -p /usr/local/bin
+ cat
+ sudo tee /usr/local/bin/locationchanger
+ sudo chmod +x /usr/local/bin/locationchanger
+ mkdir -p /Users/nathanblais/Library/LaunchAgents
+ cat
+ launchctl load /Users/nathanblais/Library/LaunchAgents/LocationChanger.plist
```

**Comment by eprev** [comment]
The output seems legit. The installation script is not supposed to create `.locations` folder (the folder is optional, if you want to configure locationchanger, then go ahead and create both the folder and the configuration file).
