### ISSUE TITLE
Run a script when the connected SSID is NOT a specific SSID

### ISSUE THREAD

**Issue by HanSooloo** [eprev/locationchanger#20]
Simple use case ... when I connect to my office network, there is a script that automatically changes my hostname to a company policy specified value.

However, when I connect to my home network, I want to use my own hostname, e.g., `X-Wing`.

As a matter of fact, I want to run this special "reset hostname" script anytime I connect to a network that is NOT a specified network/SSID.

Ideally, I would be able to define a network location with a `!<network_name>` style.

**Comment by eprev** [comment]
`locationchanger` is not meant to be a Swiss army knife. It works around Network Locations, not Wi-Fi networks per se. Whenever Mac connects to a Wi-Fi network it does not have a network location for, it will switch to `Automatic` location and will run `~/.locations/Automatic` script if the later exists. You may think of that one as `!<network_name>`. Hope it helps.
