### ISSUE TITLE
Network location not changing

### ISSUE THREAD

**Issue by mousetail85** [eprev/locationchanger#3]
I've tried your install script, but I get the service already loaded. 
LocationChanger.plist: service already loaded

Can you let me now how I can uninstall your program, so I can reinstall it?

**Comment by eprev** [comment]
There's no need to uninstall it. Okay, looks like it was installed correctly. What network locations did you create? And what's the name of the Wi-Fi you're connecting to?

**Comment by mousetail85** [comment]
The name of my home and office networks are the same name I gave the network locations in System preferences, including capitals and all..

**Comment by eprev** [comment]
No cooperation, closing it.
