### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Mollium** [eprev/locationchanger#6]
While installing LocationChanger by using the 
"curl -L https://github.com/eprev/locationchanger/raw/master/locationchanger.sh | bash" command in terminal. 

**After I enter my root password I get the error below:**

bash: line 11: /usr/local/bin/locationchanger: Permission denied
chmod: /usr/local/bin/locationchanger: No such file or directory

**If I try it again, the error below pops up:**

bash: line 11: /usr/local/bin/locationchanger: Permission denied
chmod: /usr/local/bin/locationchanger: No such file or directory
/Users/xxx/Library/LaunchAgents/LocationChanger.plist: service already loaded

<img width="571" alt="schermafbeelding 2017-12-14 om 16 10 13" src="https://user-images.githubusercontent.com/6764014/33998998-82af79d2-e0e9-11e7-870e-2a64cff94463.png">

Can you help me fix this?

Thanks in advance!

**Comment by eprev** [comment]
What does `stat /usr/local/bin` say?

**Comment by eprev** [comment]
Thanks. This is odd, try `sudo chmod g+w /usr/local/bin` (this will make that folder writable for admins) and install it again.

**Comment by Mollium** [comment]
It keeps giving me the same error, very odd.
Seems like I can't get permission while I'm using the admin account on my MacBook.

<img width="573" alt="schermafbeelding 2017-12-14 om 17 01 58" src="https://user-images.githubusercontent.com/6764014/34001697-f1ae1b2a-e0f0-11e7-8351-376973f02b4d.png">

**Comment by eprev** [comment]
Okay, then mods might be incorrect on other levels. What do `stat /usr/local` and `stat /usr` say?

**Comment by eprev** [comment]
Or maybe you could try to create that file manually first: `sudo touch /usr/local/bin/locationchanger` and `sudo chmod g+wx /usr/local/bin/locationchanger`, and then install it again.

**Comment by Mollium** [comment]
I tried both the stat commands, and after that tried both of the sudos you gave me.
After doing this, Terminal showed me the information below. Doesn't seem it wants to give me permission, never had this kind of problem before --' 

Do you know what could cause this?

<img width="621" alt="schermafbeelding 2017-12-14 om 17 21 27" src="https://user-images.githubusercontent.com/6764014/34002769-cf6a6e8a-e0f3-11e7-9377-dca4767e6b43.png">

**Comment by eprev** [comment]
Hard to say. You can manually install it though. Just save https://gist.github.com/eprev/84c4a658277c6e0244d9367711e61837 as `/usr/local/bin/locationchanger`.

**Comment by Mollium** [comment]
I think I got it working, but I have to test it at home when connecting with my home network.
Where can I place the aliasing files and scripts, because when I copy ~/.locations/ to my pathfinder, it takes me to my Home folder.

**Comment by eprev** [comment]
Just replace `~` with the full path to your home folder (`/Users/xxx/`).

**Comment by eprev** [comment]
Hey, @Mollium. I managed to reproduce the problem and pushed the fix for it, sorry for your troubles and thanks for raising this issue.
